### ISSUE TITLE
genGenomeFromAGP help needed

### ISSUE THREAD

**Issue by agroppi** [csiro-crop-informatics/biokanga#13]
I have a draft assembly in scaffolds (61)
With the help of genetics markers I have ordered these scaffolds.
The results generated by the script I have used is a agp file.

I want to use genGenomeFromAGP to construct the draft genome in linkage groups (chromosomes).

But I have a doubt about the input files needed as described in `genGenomeFromAGP --help`

Is this command line correct ? : 

`genGenomeFromAGP  -f 4 -F mylogfile.log -m 1 -i scaffolds.fasta -I ordered_scaffolds.agp -o chomosome_assembly.fasta`

Thanks

**Comment by kit4b** [comment]
To generate a scaffolded assembly (could still be gaps dependent on the completeness of the components and associated types in your AGP ) from the component sequences in your <scaffolds.fasta> using <ordered_scaffolds.agp> then change '-m 1' to be '-m 0' .

 '-m 1' is only used when you have an AGP for the generated assembly and you wish to know the component names and start/end offsets of these components in the generated assembly. This is dependent on the generated assembly being derived from an <ordered_scaffolds.agp>. 
The output, when using '-m 1' is a CSV file containing 4 fields -
1)   The super contig name ( could be a chromosome or named sequence ) in the assembly
2)   The component name
3)   Starting offset of component in the super contig
4)   Ending offset of component in the super contig

Please let us know if you have further questions.

**Comment by agroppi** [comment]
Thank you for detailed answser.

I have now the following error : 
```
[May 24 10:44:41.176 2018](genGenomeFromAGP) Version: 1.1.0 Processing parameters:
        Processing mode is : 'standard genome AGP generation'
[May 24 10:44:41.179 2018](genGenomeFromAGP) Errors whilst parsing line 'lg1	7280203	7280302	2	U	100	scaffold	yes	map' - ordered_scaffolds.agp
[May 24 10:44:41.179 2018](genGenomeFromAGP) Exit code: 1 Total processing time:     00:00:00.000 seconds
```
I suppose something is wrong in my agp file (here attached) ?

[ordered_scaffolds.zip](https://github.com/csiro-crop-informatics/biokanga/files/2034528/ordered_scaffolds.zip)

**Comment by kit4b** [comment]
I think your AGP file is correctly formatted according to the latest AGP 2.0 file specification. 
Problem is with how genGenomeFromAGP is parsing the 2.0 format as genGenomeFromAGP is expecting AGPs conformant with the earlier 1.1 AGP file specification.  See - https://www.ncbi.nlm.nih.gov/assembly/agp/AGP_Specification/ - for specification details and differences from earlier 1.1 specification.
We will treat your issue as being a bug in the current biokanga toolkit and ensure both AGP 2.0 and 1.1 can be transparently handled. I can't give a release date for the fix but it should be sometime next week.
Please let us know if you have further questions.

**Comment by alexwhan** [comment]
@agroppi please see the latest release of the toolkit v4.3.10 which includes v1.2.0 of genGenomeFromAGP that Stuart has updated to handle AGP 2.0

**Comment by agroppi** [comment]
@alexwhan thank you very much.
I will try this new version and keep you informed.

**Comment by agroppi** [comment]
@alexwhan It works perfectly with a file in AGP 2.0 format 
Thank you !
