### ISSUE TITLE
Bug: Blitz alignment outside of target sequence length

### ISSUE THREAD

**Issue by spriggsy83** [csiro-crop-informatics/biokanga#22]
I've stumbled upon an interesting bug in a Biokanga Blitz result (Version 4.3.9)- an alignment block is reported that sits wholly beyond the end of the target sequence.
```
strand qName qSize qStart qEnd tName tSize tStart tEnd blockCount blockSizes qStarts tStarts
-  query  1345  44  1290  target  55537  20104  81702  2  337,781,  55,520,  20104,80921,
```
Note that the target sequence is only 55,537 bp (confirmed), but the second alignment block starts at 80,921 bp and overall alignment goes to 81,702 bp.

A pairwise BLAST confirms the presence and location of the first alignment block, but of course not the second.

I have at least 6 more examples of same issue having occurred.  However, testing a one-to-one alignment of this query to this target does not replicate the issue; it's only happening when part of a larger scale process.

**Comment by spriggsy83** [comment]
Interesting addition: multiple queries, from multiple samples, from multiple different runs of Blitz, are all reporting similar blocks outside the _same_ target sequences.  Perhaps the issue lies within the indexed targets .sfx file that these Blitz runs all had in common?

**Comment by kit4b** [comment]
I would be surprised if the issue relates to the indexing.
Anything special about the targets, is it possible that the query sequence is actually split over multiple targets e.g. you are aligning a query sequence against an assembly/transcriptome containing adjacent multiple individual target sequences  each of which partially overlap? Could be Blitz has overlooked the boundary marker between adjacent target sequences, target1 and target2, and is attributing the 2nd block alignment in target2 to target1 using the offset into target2 as though it was still within target1.
What was the parameterisation used and is the log file available?

**Comment by spriggsy83** [comment]
I’ve just found that the bug can be replicated using only a single example query sequence as input.  Result and input attached.  
[tmp1.fasta](https://github.com/csiro-crop-informatics/biokanga/files/2601870/tmp1.fasta.txt)
[testSeq_vs_cowpeaGenome.blitz.P1.log](https://github.com/csiro-crop-informatics/biokanga/files/2601867/testSeq_vs_cowpeaGenome.blitz.P1.log)
[testSeq_vs_cowpeaGenome.blitz.P1.txt](https://github.com/csiro-crop-informatics/biokanga/files/2601868/testSeq_vs_cowpeaGenome.blitz.P1.txt)

Reference was the Cowpea genome.  A fresh version of ‘Vigna unguiculata v1.1’ genome release may be downloaded from https://phytozome.jgi.doe.gov/pz/portal.html (requires login, free registration).

Initial test command was:
```
biokanga blitz  --querylendpct=50 --maxpathstoreport=1 --sensitivity=3 \
-i tmp1.fasta \
-I CowpeaDB/closeCowpeaPhytosome1.1/Vung1.1.genome.sfx\
-F testSeq_vs_cowpeaGenome.blitz.log -o testSeq_vs_cowpeaGenome.blitz.txt
```

Of note, the reported alignment would actually fail the ‘query length percent aligned > 50’ check, if it wasn’t for the extra phantom block of alignment.
Same result still occurs if --querylendpct=25.

Setting maxpathstoreport=2 (the .P2 results attached) result in a second alignment to be reported, but the first alignment still contains the incorrect block.
[testSeq_vs_cowpeaGenome.blitz.P2.log](https://github.com/csiro-crop-informatics/biokanga/files/2601865/testSeq_vs_cowpeaGenome.blitz.P2.log)
[testSeq_vs_cowpeaGenome.blitz.P2.txt](https://github.com/csiro-crop-informatics/biokanga/files/2601866/testSeq_vs_cowpeaGenome.blitz.P2.txt)

Same result also still occurs at sensitivity mode settings of 0 and 1.  However, goes away when sensitivity mode = 2 (high sensitivity)!
[testSeq_vs_cowpeaGenome.blitz.s2.log](https://github.com/csiro-crop-informatics/biokanga/files/2601893/testSeq_vs_cowpeaGenome.blitz.s2.log)
[testSeq_vs_cowpeaGenome.blitz.s2.txt](https://github.com/csiro-crop-informatics/biokanga/files/2601894/testSeq_vs_cowpeaGenome.blitz.s2.txt)
