### ISSUE TITLE
Segfault with pemode 3

### ISSUE THREAD

**Issue by rsuchecki** [csiro-crop-informatics/biokanga#28]
Version: 4.4.0+

```
[Apr 11 16:01:37.367 2019](biokanga) Paired end association and partner alignment processing started..
[Apr 11 16:01:37.381 2019](biokanga) Generating paired reads index over 246 paired reads
[Apr 11 16:01:37.384 2019](biokanga) Starting to associate Paired End reads to be within insert size range ...
[Apr 11 16:01:37.387 2019](biokanga) Processed putative 0 pairs, accepted 0Segmentation fault (core dumped)
```

Steps to reproduce:

```
curl ftp://ftp.ensemblgenomes.org/pub/plants/release-40/fasta/oryza_sativa/dna/Oryza_sativa.IRGSP-1.0.dna.chromosome.10.fa.gz \
| gunzip --stdout > O_sativa_IRGSP-1.0_Chr10.fasta

biokanga index \
  --threads 2 \
  -i O_sativa_IRGSP-1.0_Chr10.fasta \
  -o O_sativa_IRGSP-1.0_Chr10.fasta.sfx \
  --ref O_sativa_IRGSP-1.0_Chr10.fasta

biokanga align   \
  --sfx O_sativa_IRGSP-1.0_Chr10.fasta.sfx   \
  --mode 0   \
  --format 5   \
  --pemode 3  \
  --in O_sativa_IRGSP-1.0_Chr10_ArtIllumina_reads.1.fq.gz   \
  --pair O_sativa_IRGSP-1.0_Chr10_ArtIllumina_reads.2.fq.gz  \
  --out out.bam   \
  --threads 2  \
  --substitutions 5
```

Reads:
[O_sativa_IRGSP-1.0_Chr10_ArtIllumina_reads.1.fq.gz](https://github.com/csiro-crop-informatics/biokanga/files/3067139/O_sativa_IRGSP-1.0_Chr10_ArtIllumina_reads.1.fq.gz)
[O_sativa_IRGSP-1.0_Chr10_ArtIllumina_reads.2.fq.gz](https://github.com/csiro-crop-informatics/biokanga/files/3067140/O_sativa_IRGSP-1.0_Chr10_ArtIllumina_reads.2.fq.gz)

**Comment by kit4b** [comment]
Please supply a copy of the log file generated prior to the segmentation fault and details on the biokanga compute resource hosting environment, these would assist in replicating the reported segfault – thanks.

**Comment by rsuchecki** [comment]
Most recently, I observed the issue on a linux VM with 2 logical cores (Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz), 6GB RAM

```
Linux 4.15.0-47-generic 16.04.1-Ubuntu x86_64 GNU/Linux
```
Previously also on standard compute nodes on pearcey HPC cluster.

Biokanga versions prior to `4.0.0` do not appear to be affected.

[biokanga.log](https://github.com/csiro-crop-informatics/biokanga/files/3071120/biokanga.log)

Hope this helps!

**Comment by kit4b** [comment]
Thanks for log details. I can replicate segfault so will investigate.
