### ISSUE TITLE
MultiQC Module for BioKanga

### ISSUE THREAD

**Issue by nathanhaigh** [csiro-crop-informatics/biokanga#6]
It might be good to have a `MultiQC` (http://multiqc.info/docs/#multiqc-modules) module written for `BioKanga`.

Links of interest:

- http://multiqc.info/docs/#coding-with-multiqc
- http://multiqc.info/docs/#writing-new-modules

**Comment by kit4b** [comment]
I had never come across MultiQC before; looks like an extremely useful results summary presentation system. One drawback may be that there seems to be a reliance on summary logs as generated by the various tools, these logs are usually non-structured and very ad-hoc in terms of their information content (I just summarised biokanga's logs! ) so when comparing results generated by different tools then it is likely that differences between these visual summaries will be difficult to interpret as to how significant these differences really are. Also if a log format is changed then pre-existing MultiQC modules will presumably fail.

**Comment by nathanhaigh** [comment]
I agree that comparison of data gleaned from the logs of different tools is not all that meaningful. However, comparison of data for a single tool is really helpful. For instance, with `BioKanga` the numbers of reads with the various BAM tag's is useful to have summarised across many input samples. Currently, I parse this out of the logs myself and plot them as stacked bars (counts and percentages) using `ggplot` in `R`.

**Comment by alexwhan** [comment]
Agreed. @nathanhaigh you may be interested in a super lightweight single purpose R package I threw together to handle some biokanga output (https://github.com/alexwhan/biokangr). I'd been thinking of building some log output parsing functionality there, but haven't got around to it

**Comment by nathanhaigh** [comment]
@alexwhan it would be nice to have a `demo` directory in there with some example output files/plots to demonstrate features.

**Comment by alexwhan** [comment]
@nathanhaigh That seems entirely reasonable! The only existing functionality was for processing blitz output, but still...

**Comment by kit4b** [comment]
Do it right <=> do it once. Why not base BioKanga MultiQC reporting off SQLite databases, treating SQLite as a common interchange format between bioinformatics toolsets. You have SQLite for blitz, and a PSL to SQLite converter already so any tool capable of generating PSL alignments could be summary reported by MultiQC with a MultiQC SQLite module. Use a SAM to SQLite (CLIPSeqTools::PreprocessApp::sam_to_sqlite - Load a SAM file in an SQLite database) generator, or add as additional output format to 'biokanga align') and NGS alignments from any aligner with SAM/BAM output could now handled by MultiQC down to whatever level of required detail. Process the CSV outputs of 'biokanga ngsqc' into SQLite and MultiQC can then immediately be used for QC summary reporting.
Obviously SQLite requires more implementation effort upfront than simple log parsing, but it would bypass the pitfalls of log file reliance I outlined earlier for summary reporting  and would allow the generated SQLite databases to be used for ease of data exploration and hypothesis testing.

**Comment by kit4b** [comment]
Just enable SQLite summary reporting when aligning with 'biokanga align' - already available in the current release - and you can query the generated SQLite dataset for the alignment summaries as well as the parameterisation used. No need to parse logs which are subject to change with each new release.

**Comment by kit4b** [comment]
This issue is really a feature request, it should be closed as the SQLite summary reporting already supplies the equivalency of the requested feature albeit a simple python script may be required to process the SQLite database and generate customised summary reporting.

**Comment by alexwhan** [comment]
Regardless, from http://multiqc.info/docs/#writing-new-modules it seems that the feature needs to be written for multiqc...
